### ISSUE TITLE
[NOMINATION]: 2023 "at large" Juliana Cafik

### ISSUE THREAD

**Issue by jcafik** [openwallet-foundation/tac#10]
Nominee Name:
Juliana Cafik
Principal Standards Architect, Microsoft
Email: julianacafik@microsoft.com

Short Personal Bio
With 28 years of experience in the technology industry, Juliana is a seasoned professional. She began her career by developing solutions for ski resorts to transport people up mountains in a simple, quick, cost-effective, and non-repudiated manner. She was also successful in leading a start-up from its very beginning to its eventual exit in the payment sector, a time when it was really considered bleeding-edge technology. Throughout her career, she has been responsible for many innovative projects, including the creation of new protocols for wireless POS and NFC devices, EMV for mobile payments, payment tokenization, access control for ticketing, fraud prevention methods, EMR systems for the healthcare industry, ERP system integrations for payment processes, biometrics for time and attendance, mobile device security, the design of a payment kernel, and a high-assurance digital wallet.

Personal Pitch 
I nominate myself, Juliana Cafik, as a member at large on the Technical Advisory Committee of the Open Wallet Foundation as a member of the Open ID Foundation.  I am currently a Principal Standards Architect at Microsoft, where I have a strong focus on governance and policy and act as a payment SME. Additionally, I am an active contributor to several working groups at OIX, and hold various leadership roles within DIACC, such as serving as Co-Chair of the Trust Framework Expert Committee, being a member of the Innovation Expert Committee, and participating in design teams for Technology & Infrastructure, Digital Wallet, and Trust Registries components. 

I genuinely believe that strong teams working together can achieve great things, and I would be honored to  contribute my technical abilities, lend my expertise in standards, governance, policy, and compliance, as well as be a tenacious member of the OWF. I am confident that with the collective effort of the community, positive outcomes can be achieved, including equitable access and user control, prioritization of safety, security, privacy, freedom of choice, portability and interoperability.

Thank you for your time,

Juliana

**Comment by tkuhrt** [comment]
Thank you for your nomination.

**Comment by jcafik** [comment]
You are so welcome!!
________________________________
