### ISSUE TITLE
Enable the "Private vulnerability reporting" for this repo 

### ISSUE THREAD

**Issue by skounis** [openwallet-foundation/tac#104]
The [documentation about the security policy](https://tac.openwallet.foundation/governance/security/#vulnerability-disclosure-process-and-associated-rules) mentions 

> All OpenWallet Foundation's projects, **including this project**

To align with this we should enable the reporting features for this repository as well 

![image](https://github.com/openwallet-foundation/tac/assets/690575/a84971be-17e1-46f8-86dc-bd16f4c2ce5b)

**Comment by ryjones** [comment]
@skounis done!
