### ISSUE TITLE
Change repo ACL

### ISSUE THREAD

**Issue by samuelmr** [openwallet-foundation/tac#107]
* Repo to change access: https://github.com/openwallet-foundation/digital-wallet-and-agent-overviews-sig
* GitHub ID to add: samuelmr

One of:

* Team to be added to: [GitHub team list](https://github.com/orgs/openwallet-foundation/teams) or [Labs GitHub team list](https://github.com/orgs/openwallet-foundation-labs/teams): GitHub team list
* Role:
	- Admin

**Comment by ryjones** [comment]
@maaikevanleuken does this look good to you?

**Comment by maaikevanleuken** [comment]
> @maaikevanleuken does this look good to you?

Yes, it does. Thank you.

**Comment by ryjones** [comment]
@samuelmr invite sent. [here is the team I added you to](https://github.com/orgs/openwallet-foundation/teams/digital-wallet-and-agent-overviews-sig-maintainers/members)
