### ISSUE TITLE
[NOMINATION]: 2023 “at large” Jeremie Miller

### ISSUE THREAD

**Issue by quartzjer** [openwallet-foundation/tac#11]
## Nominee
Jeremie Miller
Principal Standards Architect, Ping Identity
jmiller@pingidentity.com

## Bio
Jeremie Miller is a pioneering software engineer and open-source advocate, best known for his groundbreaking work in the development of Jabber. His work on Jabber laid the foundation for the development of the Extensible Messaging and Presence Protocol (XMPP), an open and extensible protocol used for real-time communication and collaboration, which now powers numerous applications and services worldwide such as WhatsApp and Zoom.

Throughout his career, Miller has demonstrated a strong commitment to the open-source community, actively contributing to various projects and advocating for the adoption of open standards. In 2010 he co-founded Singly, a company focused on developing an open source effort around personal data lockers. Later, he worked on TeleHash, a decentralized and encrypted peer-to-peer communication protocol aimed at securing online privacy.

Jeremie Miller continues to innovate and contribute to the ever-evolving technology landscape, with a keen focus on enhancing privacy, security, and open standards for the digital age. He is actively developing new Zero-Knowledge Proof (ZKP) standards in the IETF as part of the JOSE WG.

## Personal Pitch
I've been eagerly following the development of the OWF since the very beginning during a conversation at Identiverse last summer. I have a strong drive to advance the state of personal privacy in the world by improving low level protocols to incorporate new cryptographic primitives.

Privacy isn't solved in just one place though and needs to be respected at every layer of the stack.  As a TAC representative, I would love the opportunity to contribute my experiences to help raise awareness of privacy considerations for all projects at the OWF.

Thank you!

_Jer_

**Comment by tkuhrt** [comment]
Congratulations on being selected as an "at large" member.
