### ISSUE TITLE
Change project visibility

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/tac#114]
* Repo to change access: https://github.com/orgs/openwallet-foundation/projects/1

we’d like to make the project public, but i don’t seem to have the needed permissions. Maybe it needs to be linked to credo repo first? We transferred it from HL github

**Comment by skounis** [comment]
@ryjones @TimoGlastra , the name of this project might be associated with the official development of the **EU Digital Wallet**. I recommend adding a description to clarify its purpose and its connection to the **European Digital Identity Wallet (EUDIW)**."

**Comment by TimoGlastra** [comment]
Sure @skounis. I'll rename it to Credo - ARF Compliance and add a short description

**Comment by TimoGlastra** [comment]
I've updated it now, please let me know if this looks good to you @skounis

**Comment by skounis** [comment]
@TimoGlastra Thank you, it looks perfect.
