### ISSUE TITLE
[NOMINATION]: 2023 “at large” Stavros Kounis 

### ISSUE THREAD

**Issue by skounis** [openwallet-foundation/tac#12]
## Nominee
Stavros Kounis
Enterprise Architect
skounis@gmail.com

## Bio
Stavros Kounis is an accomplished software engineer and entrepreneur with over 20 years of experience in designing and building software. He holds an engineering degree and has extensive expertise in web and mobile technologies. Throughout his career, Kounis has founded two software companies, both of which delivered products with significant impact in their respective markets. He is a strong supporter and advocate of open-source software, as demonstrated by his recognition by the Eclipse Foundation in 2010. Currently, he serves as an Enterprise Architect at the European Commission, where he is involved in all aspects of building and delivering the EU Digital Covid Certificates worldwide, as well as supporting the development of the EU Digital Identity Wallet and its open-source strategy.

## Personal Pitch
I have been closely following the formation of the Open Wallet Foundation since its early days, and I am thrilled to have the opportunity to contribute to its mission. My experience in governance, operations, and development, gained through my work on establishing the EUDCC as a global standard, will be a valuable asset to the Technical Advisory Council. I am passionate about open standards and believe that the bridge between the OWF initiative and the EU Digital Identity Wallet will benefit both. As a member of the TAC, I look forward to sharing my unique perspectives and experiences to advance the goals of the Open Wallet Foundation.

I hereby nominate myself in my personal capacity as a professional and clarify that I will not represent the European Commission in any way. 

Thank you,
Stavros

**Comment by tkuhrt** [comment]
Congratulations on being selected as an "at large" member.
