### ISSUE TITLE
[NOMINATION]: 2024 "at large" David Luna

### ISSUE THREAD

**Issue by dave-luna** [openwallet-foundation/tac#129]
# Nomination 🗳️

## Nominee Name
David Luna
https://github.com/dave-luna

## Short Personal Bio
David Luna serves in a leadership position as Product Architect and Subject Matter Expert for the PingOne Neo product suite at Ping Identity. There, he supports the implementation of standards and drives innovation around verifiable credentials, digital wallets, and decentralised identity. Previously, David was instrumental in architecting and developing ForgeRock's Access Manager product used by Fortune 1000 corporations globally, and subsequently reported as an emerging technology research engineer in the office of the CTO. David has a Master's Degree in Computer Science from the University of Southampton.

## Short Personal Pitch
I wish to increase my involvement and contributions to the Open Wallet Foundation through membership of the Technical Advisory Committee. I bring my experience speaking to enterprises and their end users, project managers, technical architects, and engineers around the adoption of digital wallets. This, in combination with my involvement in the development of standards and the code that interacts with them makes me a suitable candidate for this position. 

I believe passionately that digital wallets and their contents will act to enable a transformative change in the way individuals interact with services and one another when sharing information, enabling new secure and convenient methods to authenticate, authorise, sign, and transact both on and offline. I have written significant components for large IAM platforms that interact across standards-based protocols, and now have a wider product- and platform-orientated view. In addition, I have a personal blog where I speak to the technology and its potential across multiple sectors. I'm looking to bring my expertise to work alongside other committed individuals to further the development of digital wallets and their contents.

Thank you for your consideration.

**Comment by tkuhrt** [comment]
Thank you for your nomination.
