### ISSUE TITLE
[NOMINATION]: 2024 "at large" Marcos Allende

### ISSUE THREAD

**Issue by AllendeMarcos** [openwallet-foundation/tac#130]
# Nomination 🗳️

## Nominee Name
Marcos Allende Lopez
@AllendeMarcos

## Short Personal Bio
Executive Director and Head of Operations at LACNet, the orchestrator of blockchain networks for Latin America and the Caribbean. CEO and Co-Founder of Blerify, a platform than enables verification infrastructure for a new generation of wallet-based interactions between governemnts, enterprises, and people. Marcos is Quantum Physicist who led the areas of blockchain, digital assets, and quantum technologies at the Inter-American Development Bank (IDB) between 2017 and 2023, which he continues to support now as an external advisor. Marcos served in leadership roles for more than 20 projects using decentralized technologies in Latin America and the Caribbean, including the first bond tokenization and some of the largest projects on verifiable credentials in the region related to identity, education, and health. During the critical COVID-19 pandemic times, Marcos Allende contributed to the WHO's Vaccination Certificates Programme and the LACPass Latin American implementation. He also actively contributed to the writing of the Good Health pass Interoperability Blueprint developed by a large working group coordinated by TrustOverIP. Post-grad studies in Quantum Computing & Cryptography at MIT, and Finance & Management at LSE. Marcos has been a professor, lecturer, and tutor at several universities, including Harvard Kennedy School, UC3M, the European Tech School, and the Three Points Digital School. Responsible for developing the first end-to-end solution for quantum resistance in EVM-compatible blockchain networks, featured in Nature’s magazine Scientific Reports. Contributions to 25+ publications on digital assets, digital identity, digital wallets, quantum cryptography, and decentralized registries in collaboration with IDB, WEF, TrustOverIP and other global thought leaders. 

## Short Personal Pitch
Since 2017 I have been contributing to multiple efforts focused on developing open standards, tools, and materials for the adoption of a new generation of digital interactions based on digital credentials, non-custodial wallets, and tokenized digital assets. I have had the privilege of actively participate in some of the most emblematic initiatives in Latin America and the Caribbean. I believe I can contribute the expertise of many years working on these area not only from the theoretical side but also with lessons learned from several real world projects, bringing to the table the peculiarities and needs of Latin America and the Caribbean, which is a region very well positioned for the adoption of the architecture and mission being developed by the OWF. I have been contributing to the OWF since 2023 and I believe in the potential of this initiative to establish a transformative framework that can set the basis large-scale interoperability.

**Comment by tkuhrt** [comment]
Thank you for your nomination.
