### ISSUE TITLE
[NOMINATION]: 2024 "at large" Jaehoon Shim

### ISSUE THREAD

**Issue by aceshim** [openwallet-foundation/tac#131]
# Nomination 🗳️

## Nominee Name
Jaehoon (Ace) Shim
@aceshim

## Short Personal Bio
Jaehoon Shim is the co-founder and CEO of Hopae. In 2021 Jaehoon and the team built COOV, the official blockchain-based COVID-19 vaccination credential system for South Korea. The system managed over 43M users daily and around 4 billion verifications with 86M edge agents nation-wide while using W3C DID and VCDM. COOV also successfully established international interoperability for mutual recognition with EU and Singapore. For his contributions, Jaehoon received commendation from the minister.

Jaehoon Shim, with a Computer Science BS from UIUC, brings experience from his time as a blockchain researcher at LG. As a founder and principal organizer of SSIMeetup Korea, he champions self-sovereign identity technologies. His work includes translating W3C's DID and VC specifications into Korean as an official version, reflecting his commitment and advocacy for a digital future.

## Short Personal Pitch
I am honored to present my candidacy for the Technical Advisory Committee, drawing from my deep-rooted involvement with the Open Wallet Foundation (OWF) since its inception. As the CEO of Hopae, a proud founding member of OWF, we've actively contributed to the foundation's mission, notably with our project SD-JWT-JS, which is currently leading the transition from lab to growth stage within the community.

My expertise extends to designing, managing, and optimizing large-scale, nation-wide systems—a skill set that I believe will serve as a valuable asset to the OWF community and its diverse projects. This experience not only underscores my technical acumen but also my ability to navigate complex challenges and drive significant advancements in technology infrastructure.

Furthermore, my active participation in the open-source community, particularly within the Asia-Pacific region, positions me uniquely to bridge gaps and foster collaboration. I am committed to leveraging my network to encourage more companies and organizations from APAC to join and enrich the OWF community.

My nomination is driven by a genuine desire to contribute to and shape the future of open web standards, ensuring they remain robust, inclusive, and forward-thinking. I look forward to the opportunity to share my insights, experience, and passion with the Technical Advisory Committee and the broader OWF ecosystem.

**Comment by tkuhrt** [comment]
Congratulations on being selected as an "at large" member.
