### ISSUE TITLE
[NOMINATION]: 2024 "at large" Michael Lodder

### ISSUE THREAD

**Issue by mikelodder7** [openwallet-foundation/tac#132]
# Nomination 🗳️

## Nominee Name
Michael Lodder
mikelodder7

## Short Personal Bio
I have a BS in Computer Engineering, MS in Electrical Engineering, and PhD in Cyber Operations. I have been working in the context of Security, Privacy, Anonimity, and Cryptography for 2 decades. I started working with Bitcoin in 2009 and Sovrin in 2016. I've been anxious to address many of the issues in this space from a technical perspective and that was part of my PhD research. I've have experience in many industries including work in US Government, Healthcare, Market research, Coinbase, Sovrin, and LIT protocol.

## Short Personal Pitch
I believe that open wallets are the key to future adoption of crypto and decentralized products like identity and MPC. Much of this relies on having a background in hardware, software, and cryptography. I've been a bridge for these industries for decades and look forward to working with others to improve the standards and collaboration.

**Comment by tkuhrt** [comment]
Thank you for your nomination.
