### ISSUE TITLE
[NOMINATION]: 2024 Chair/Vice Chair Stavros Kounis

### ISSUE THREAD

**Issue by skounis** [openwallet-foundation/tac#139]
# Nomination 🗳️

## Nominee Name
Stavros Kounis
[skounis](https://github.com/skounis)

## Short Personal Bio
Stavros is a dedicated and proactive member of the Technical Advisory Council (TAC) with a strong commitment to advancing the mission of the Open Wallet Foundation (OWF). With a background in software engineering and open source practices, Stavros brings valuable insights and a wealth of experience to the TAC.

## Short Personal Pitch
I am honored to nominate myself for the position of Chair/Vice-Chair of the Technical Advisory Council (TAC) of the Open Wallet Foundation (OWF). Throughout my tenure as a TAC member, I have demonstrated a deep commitment to advancing the goals and objectives of OWF, contributing actively to discussions, providing valuable feedback on project proposals. I am also actively participating in the development of the Architecture Reference Framework for the European Digital Wallet and its ecosystem.

My involvement in the development of the European Digital Covid Certificates and the European Digital Identity Wallet has provided me with significant experience in governance, management, and open-source practices. I have played a key role in planning, establishing, and implementing open-source policies for these projects, ensuring transparency, inclusivity, and collaboration.

I strongly believe in the power of communities and the importance of mutual respect in fostering collaboration and innovation. I welcome the diversity of voices and perspectives that each individual brings to the table and believe that the balance between different opinions is essential for success.

As Chair/Vice-Chair, I will strive to create an inclusive and collaborative environment within the TAC, where all members feel valued and heard. I will promote focused discussions, encourage collaboration on specific tasks, and ensure that all efforts are acknowledged and credited appropriately. My goal is to contribute to making OWF the point of reference in the industry for fostering openness and usefulness in the domain of digital identity.

Thank you for considering my nomination. I look forward to the opportunity to serve the Open Wallet Foundation and the TAC community.

**Comment by tkuhrt** [comment]
Congratulations on vice chair role
