### ISSUE TITLE
Transfer a repo - Trust Spanning Protocol

### ISSUE THREAD

**Issue by tkuhrt** [openwallet-foundation/tac#150]
* GitHub repo to transfer: https://github.com/wenjing/rust-tsp
* Project to be added to: New lab (tsp)
* Teams with access: 
	* Team name: New Team (`tsp-maintainers`) on [openwallet-foundation-labs](https://github.com/orgs/openwallet-foundation-labs/teams)
	* Role:
		- Manage
         * Initial Maintainers
                 - Marlon Baeten: @marlonbaeten
                 - Marc Schoolderman: @squell
                 - Wenjing Chu: @wenjing

Need to work with @wenjing to determine how DCO will be resolved.

**Comment by tkuhrt** [comment]
@wenjing : If you would prefer that we create a new repo and have you manually transfer the code, please do let us know.

**Comment by wenjing** [comment]
@tkuhrt @ryjones Can you create the repo, named "tsp", and add three of us as maintainers, except change Marc's github to "tweedegolf-marc"? We are then ready to make one clean commit with all DCO sigoffs. Will that work?

**Comment by tkuhrt** [comment]
@ryjones : Yes, I will take care of this after the Hyperledger call today.

**Comment by tkuhrt** [comment]
https://github.com/openwallet-foundation-labs/governance/pull/8 -- @wenjing : Can you please accept the invitation to the openwallet-foundation-labs organization?

**Comment by ryjones** [comment]
@tkuhrt he doesn't have one

**Comment by tkuhrt** [comment]
@ryjones : I manually added an invitation: https://github.com/orgs/openwallet-foundation-labs/people/pending_invitations

**Comment by tkuhrt** [comment]
https://github.com/openwallet-foundation-labs/tsp

**Comment by skounis** [comment]
@wenjing @tkuhrt 

I've noticed that the old repository remains accessible without any redirection or notice indicating the migration. 

* https://github.com/wenjing/rust-tsp

Perhaps we should leave this ticket open until the redirection is addressed?

**Comment by tkuhrt** [comment]
@skounis : since the repo was not transferred via GitHub but manually, the best that we can do is remove the repo in its previous location to avoid confusion.

**Comment by tweedegolf-marc** [comment]
The old repository is now a (manual) redirect.
