### ISSUE TITLE
Transfer a repo - Tuvali

### ISSUE THREAD

**Issue by tkuhrt** [openwallet-foundation/tac#151]
* GitHub repo to transfer: https://github.com/mosip/tuvali
* Project to be added to: New lab (`tuvali`)
* Teams with access:
	* Team name: New Team (`tuvali-maintainers`) on [openwallet-foundation-labs](https://github.com/orgs/openwallet-foundation-labs/teams)
	* Role:
		- Manage
         * Initial Maintainers
                 - Sasikumar @gsasikumar
                 - Chandra @ckm007
                 - Swati @swatigoel

**Comment by gsasikumar** [comment]
We can simply transfer the project to the new org, Will that work?


Thanks
Sasikumar Ganesan
https://github.com/gsasikumar/
https://www.linkedin.com/in/sasikumarganesan/
https://twitter.com/g_sasi_kumar

**Comment by tkuhrt** [comment]
> We can simply transfer the project to the new org, Will that work?

@gsasikumar : Yes, if the repository has DCO sign-off on all commits. Please see: https://github.com/openwallet-foundation/project-proposals?tab=readme-ov-file#fixing-dco-on-existing-repositories for details.

**Comment by tkuhrt** [comment]
Created [https://github.com/openwallet-foundation-labs/tuvali via https://github.com/openwallet-foundation-labs/governance/pull/](https://github.com/openwallet-foundation-labs/governance/pull/10)
