### ISSUE TITLE
Special Interest Group Proposal: Credential Format Comparison

### ISSUE THREAD

**Issue by tlodderstedt** [openwallet-foundation/tac#26]
### Introduction/background material

I would like to propose a SIG dedicated to maintaining information about available credential formats for the benefit of OWF projects and the wider community. The topic is more complex than one might assume on first sight, since there are more than 14 formats for representing digital credentials and most of those formats can be combined with different signature algorithms, ways to represent cryptographic keys (with alone more than a hundred DID methods), status management methods, trust management methods and so on.  

There is pre-existing work started at Internet Identity Workshop (IIW 34, Spring 2022) and extended and augmented during Rebooting the Web of Trust (RWOT-XI, The Hague, Sept 2022). 

It consists of a sheet, the “credential format comparison matrix”, containing information about the technical options in the different dimensions (formats, signature algorithms, …) as well as known credential profiles, i.e. concrete combinations used in implementations and an article explaining the “matrix”. 

Sheet: https://docs.google.com/spreadsheets/d/1X93ptJcmfX1NZEo5E7ElnqJ-knDS4Dj6JOYSJ_2PsUw

Article: https://github.com/WebOfTrustInfo/rwot11-the-hague/blob/master/final-documents/credential-profile-comparison.pdf
Source Code: https://github.com/vcstuff/credential-profile-comparison

The sheet is maintained by an informal group of maintainers, who would donate it to the new SIG in order to give it a long term home. Those maintainers would also be willed to continue their work to maintain the information and are seeking for more contributors. 

### Objectives

The aim of the SIG is to provide information and tools to facilitate transparency of the technical options regarding credential formats and adjacent technologies in order to allow for comparison and effective decision making on credential formats. 

### List of deliverables or work products (optional)

The SIG shall maintain, evolve, and publish the credential format comparison matrix based on contributions from the wider identity community. 

### Leader

Mirko Molik

### Initial Participant List

Paul Bastian
Mirko Molik
Maaike van Leuken
Andre Kudra
Torsten Lodderstedt

**Comment by tkuhrt** [comment]
**Approved by TAC on May 31, 2023**

- [ ] Create Discord channel - @tkuhrt 
- [ ] Work with Torsten to get GitHub repo transferred to OpenWallet Foundation - @tkuhrt @tlodderstedt 
- [ ] Determine leader of the SIG @tlodderstedt 
- [ ] Add information about Special Interest Groups to [TAC website](https://openwallet-foundation.github.io/tac/) - @tkuhrt 
- [ ] Add link to the above to the [OpenWallet Foundation GitHub Profile](https://github.com/openwallet-foundation/.github/blob/main/profile/README.md) - @tkuhrt

**Comment by cre8** [comment]
@tkuhrt can you create a github repo so I can fill it with content?

@tlodderstedt you haven't created already one, have you?

**Comment by tlodderstedt** [comment]
Am 24. Juni 2023, 13:33 +0200 schrieb Mirko Mollik ***@***.***>:
	@tkuhrt can you create a github repo so I can fill it with content?
@tlodderstedt you haven't created already one, have you?

I haven’t.

**Comment by tkuhrt** [comment]
Created https://github.com/openwallet-foundation/credential-format-comparison-sig
