### ISSUE TITLE
Special Interest Group Proposal: Digital Wallet and Agent Overviews

### ISSUE THREAD

**Issue by maaikevanleuken** [openwallet-foundation/tac#56]
### Introduction/background material

Currently, there is a large variety of digital wallets in circulation, each working technically differently and achieving different levels of privacy, security and user-friendliness. TNO has developed an [SSI Wallet Overview](https://tno-ssi-lab.github.io/wallet-overview/), that, for each wallet, gives insight into its characteristics, filled in by the developer of the wallet. This work was presented, amongst others, at DICE 2023, where multiple experts showed their interested, including Findynet's CTO, who is now an active contributor. 

We would like to propose a SIG dedicated to maintaining the digital wallet overview for the benefit of OWF projects and the SSI community as a whole.

### Objectives

The objectives of this SIG is to further develop and maintain the Digital Wallet Overview and making a similar overview for digital identity agents/SDKs. These overviews should provide transparency of the characteristics of wallets and agents in order to allow for comparison and effective decision making on which wallet is applicable for your use case. By creating awareness of these overviews, this work can lead to less fragmentation of the SSI playing field and increase adoption.

It also offers insight into which wallets work in a similar fashion and are compliant with certain interop profiles.

To that end, the overviews should be as objective, correct and complete as possible. Therefore we will populate the overviews with the wallet / agent vendor and / or validate the results with them. 

### List of deliverables or work products (optional)

The foreseen deliverables are
- A description of the most important terminology. In particular, we need to define how *wallets* and *agents* relate.
- An agent overview.  

The SIG shall maintain, evolve and publish the overviews.

### Leader

[Maaike van Leuken](https://www.tno.nl/en/about-tno/our-people/maaike-leuken/)

### Initial Participant List

[David Alexander](https://www.linkedin.com/in/davidealexander/), Mydex
[Willem de Kok](https://www.linkedin.com/in/willem-de-kok-a74942187/), TNO
[Maaike van Leuken](https://www.tno.nl/en/about-tno/our-people/maaike-leuken/), TNO
[Samuel Rinnetmäki](https://www.linkedin.com/in/samuel/), Findynet

**Comment by tkuhrt** [comment]
@maaikevanleuken : Thanks for this proposal. We will add this to the agenda for the September 20th TAC call. It would be great if you would be available to answer any questions during that call.

**Comment by maaikevanleuken** [comment]
@tkuhrt thank you Tracy, I will be there.

**Comment by tlodderstedt** [comment]
Thanks for the proposal. I think a clarification about what a wallet does and how that differs from an agent is desperately needed.

**Comment by davidejalexander** [comment]
I would like to join this SIG. Happy to review current analysis matrix @maaikevanleuken 
Glad to see the name changed to Digital Wallets and Agents

**Comment by tkuhrt** [comment]
**Accepted by the TAC on September 20, 2023.**

Created #digital-wallet-and-agent-overviews-sig in [Discord](https://discord.gg/openwalletfoundation).

**Comment by tkuhrt** [comment]
Created repo for this SIG: https://github.com/openwallet-foundation/digital-wallet-and-agent-overviews-sig
