### ISSUE TITLE
Transfer Aries JavaScript Docs

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/tac#88]
Please include:

* GitHub repo to transfer:
https://github.com/hyperledger/aries-javascript-docs
* Project to be added to: 
Agent Framework JavaScript
* Teams with access: (examples [on GitHub team list](https://github.com/orgs/openwallet-foundation/teams) or [on Labs GitHub team list](https://github.com/orgs/openwallet-foundation-labs/teams))
	* Team name: https://github.com/orgs/openwallet-foundation/teams/agent-framework-javascript-maintainers
	* Role:
		- Manage

For now it can be named agent-javascript-docs

**Comment by ryjones** [comment]
done!
