### ISSUE TITLE
[NOMINATION]: 2023 "at large" Sebastian Elfors

### ISSUE THREAD

**Issue by Sebastian-Elfors-IDnow** [openwallet-foundation/tac#9]
<h1>Nomination 🗳️</h1> 
<b>Nominee name:</b>

Sebastian Elfors
Senior Architect, IDnow
Email: sebastian.elfors@idnow.io

<b>Personal bio:</b>
Sebastian has worked more than 25 years in the PKI industry with standardization, professional services, and product development. His technical competences are in the area of authentication, electronic signatures, and SaaS cloud computing. In addition to the technology industry, he has experience in regulatory compliance, audits, and certifications of security products. In particular, Sebastian is specialized in eIDAS compliant eID schemes and Qualified Trust Services.

In addition to being a member of OpenWallet Foundation, Sebastian is also a member of standardization organizations such as ETSI ESI, CEN TC/224, the Linux Foundation, the FIDO Alliance and W3C. In those standardization organizations he has contributed to several standards the specifies the EUDI Wallet interfaces, remote identity proofing, selective disclosure, and verifiable credentials. He is also the editor of three FIDO Alliance white papers on eIDAS and has contributed to publications issued by IATA and Bitkom.

Sebastian has a Master of Science degree in applied physics and electrical engineering from the Linköping University in Sweden and performed his master's thesis at the University of Twente in The Netherlands. Before joining IDnow, Sebastian worked at Yubico with the WebAuthn authentication standard, at TrustWeaver with the remote signing QTSP, and at SmartTrust, Nexus and ID2 Technologies with building up national certification authorities such as A-Trust and D-Trust.

<b>Short personal pitch:</b>
Sebastian would be a good choice for the seat in OpenWallet Foundation TAC given his long experience in the PKI industry, his contributions to the EUDI Wallet standardization, and his vast network with regulators and technical experts in the EU. Sebastian can play a key role with bridging the gap between the EUDI Wallet development and the OpenWallet Foundation.

**Comment by tkuhrt** [comment]
Thank you for your nomination.
