### ISSUE TITLE
Rename repositories

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/tac#98]
We've decided on the new name for Agent Framework JavaScript: Credo

We're now in the process of renaming all projects and repositories and thus we need some help with the actual github project rename:

- `agent-framework-javascript` -> `credo-ts`
- `agent-framework-javascript-ext` -> `credo-ts-ext`
- `agent-javascript-docs` -> `credo-ts-docs`

cc @karimStekelenburg

**Comment by ryjones** [comment]
https://github.com/openwallet-foundation/agent-framework-javascript/pull/1703
https://github.com/openwallet-foundation/agent-javascript-docs/pull/142
https://github.com/openwallet-foundation/agent-framework-javascript-ext/pull/232

**Comment by TimoGlastra** [comment]
Ah i could've done that myself. Thanks 🙏
